# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/AdamIsrael"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/AdamIsrael"

[social.params]
icon = "brand-twitter"


[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://linuxlab.sh/@adam"

[social.params]
icon = "brand-mastodon"
